const boards = [
  {
    id: 1,
    title: "[공지] 자유 게시판 이용 안내",
    date: "2024-11-01",
    author: "운영팀",
    content: "모두가 이용하는 자유게시판입니다. 매너를 지켜주세요!",
    views: 13,
    comments: 7,
    likes: 7,
    boardImg: "",
  },
  {
    id: 2,
    title: "ㅎㅇ 1빠요",
    date: "2024-11-01",
    author: "엄준식",
    content: "개꿀따리 꿀꿀따!!",
    views: 111,
    comments: 1,
    likes: 18,
    boardImg: "",
  },
  {
    id: 3,
    title: "롤멘토 구함",
    date: "2024-11-01",
    author: "65년생 강대근 할아버지",
    content: "탑 갑니다",
    views: 222,
    comments: 12,
    likes: 99,
    boardImg: "",
  },
  {
    id: 4,
    title: "옛날 옛적엔 놀토가 있었다는게 사실인가여?",
    date: "2024-11-01",
    author: "응애",
    content: "ㄹㅇ인가여?",
    views: 10,
    comments: 3,
    likes: 1,
    boardImg: "",
  },
];

export default boards;
